os: linux
dist: bionic

language: java
jdk: openjdk8

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x gradlew
  - curl -fsSL https://get.docker.com | sh
  - docker login --username $DOCKER_USERNAME --password $DOCKER_TOKEN
  - docker buildx version
  - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
  - docker buildx create --use --name mybuilder

script: ./gradlew build --console=plain

deploy:
  provider: script
  script: ./gradlew publishMultiArchImages --console=plain
  skip_cleanup: true
  on:
    branch: master
    tags: true
