version: "3.7"

networks:
  mongo-net:

services:

  dragalia-bot:
    image: lamba92/dragalia-telegram-bot
    networks:
      - mongo-net
    deploy:
      restart_policy:
        condition: any
    depends_on:
      - mongo-db
    environment:
      - BOT_TOKEN=${DRAGALIA_KEY}
      - DB_HOST=mongo-db
      - DB_PORT=27017

  mongo-db:
    image: mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
    networks:
      - mongo-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 15s
    ports:
      - target: 27017
        published: 27020
        protocol: tcp
        mode: ingress
